# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0bFUaefP0dZGyvzv71ePqX-rpHvJd4-
"""

import numpy as np

np.__version__

arr1 = np.arange(50) # 0 to 49
arr1, arr1.dtype

arr2 = np.random.randint(0, 50, 50)
arr2, arr2.dtype

len(arr2)

arr3 = np.random.rand(50)
arr3, arr3.dtype

new_array1 = arr1 + 10 * np.random.randn(50)
new_array1

print(arr3)
new_array2 = np.abs(arr3 * 100)
new_array2

